### ISSUE TITLE
Working together to control hardware schedule on LAN device

### ISSUE THREAD

**Issue by EricSeynaeve** [zdazzy/eg-pyms-lan#2]
I have just put up my code for controlling the USB version of EG-PMS2, including the hardware schedules: https://github.com/EricSeynaeve/sispy

I was wondering whether you were interested to work together and see if we could also control the hardware schedules on the LAN version.

I don't have the actual hardware though.

**Comment by zdazzy** [comment]
It's been some time since I last looked at how the schedule works. But I was under the impression that it's not worth the time because it's very limited, it doesn't work consistently and is completely lost when the strip itself is powered off. A regular cron job on a separate device along with the simple socket switching script (such as mine) is far better.

But if you are pretty determined to write a comprehensive library I can provide you with an address and a port which I will forward to the device and you figure everything out on your own.
